apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "3proxy.fullname" . }}
  labels:
{{- include "3proxy.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.http.enabled }}
    - name: {{ .Values.service.http.portName }}
      port: {{ .Values.service.http.port }}
      targetPort: http-proxy
      protocol: TCP
    {{- end }}
    {{- if .Values.service.socks.enabled }}
    - name: {{ .Values.service.socks.portName }}
      port: {{ .Values.service.socks.port }}
      targetPort: socks-proxy
      protocol: TCP
    {{- end }}
  selector:
    {{- include "3proxy.selectorLabels" . | nindent 4 }}
