name: Document Charts

on:
  pull_request:

jobs:
  document:
    runs-on: ubuntu-latest
    name: helm-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Install helm-docs
        env:
          version: 1.13.1
        run: |
          echo "Installing helm-docs version $version"
          curl -L -o helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/v${version}/helm-docs_${version}_Linux_x86_64.tar.gz"
          tar -xzvf helm-docs.tar.gz helm-docs
          rm -rf helm-docs.tar.gz

      - name: Run helm-docs
        run: |
          ./helm-docs --chart-search-root=charts --template-files=README.md.gotmpl

      - name: Commit results
        run: |
          set -xe
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit charts/*/README.md -m 'Update helm-docs and README.md' || echo "No changes to commit"

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
